pdftotext $1 - | gsed 's/\xe2\x80\x8b\x20//g' | gsed 's/\xe2\x80\x8b//g' | egrep -o "\S+ ?\($2[A-Za-z'’,\-]+$3\)" | sed 's/(/,(/g' | sed 's/ ,/,/g'
pdftotext $1 - | gsed 's/\xe2\x80\x8b\x20//g' | gsed 's/\xe2\x80\x8b//g' | egrep -o "\S+ \S+ ?\($2[A-Za-z'’,\-]+ [A-Za-z'’,\-]+$3\)" | sed 's/(/,(/g' | sed 's/ ,/,/g'
pdftotext $1 - | gsed 's/\xe2\x80\x8b\x20//g' | gsed 's/\xe2\x80\x8b//g' | egrep -o "\S+ \S+ \S+ ?\($2[A-Za-z'’,\-]+ [A-Za-z'’,\-]+ [A-Za-z'’,\-]+$3\)" | sed 's/(/,(/g' | sed 's/ ,/,/g'
pdftotext $1 - | gsed 's/\xe2\x80\x8b\x20//g' | gsed 's/\xe2\x80\x8b//g' | egrep -o "\S+ \S+ \S+ \S+ ?\($2[A-Za-z'’,\-]+ [A-Za-z'’,\-]+ [A-Za-z'’,\-]+ [A-Za-z'’,\-]+$3\)" | sed 's/(/,(/g' | sed 's/ ,/,/g'
pdftotext $1 - | gsed 's/\xe2\x80\x8b\x20//g' | gsed 's/\xe2\x80\x8b//g' | egrep -o "\S+ \S+ \S+ \S+ \S+ ?\($2[A-Za-z'’,\-]+ [A-Za-z'’,\-]+ [A-Za-z'’,\-]+ [A-Za-z'’,\-]+ [A-Za-z'’,\-]+$3\)" | sed 's/(/,(/g' | sed 's/ ,/,/g'
